### ISSUE TITLE
Junit realtime should display a progress bar

### ISSUE THREAD

**Issue by timja** [jenkinsci/junit-realtime-test-reporter-plugin#22]
_Originally reported by @dcendents in [JENKINS-50048](https://issues.jenkins.io/browse/JENKINS-50048)_

It would be great if the junit realtime plugin could display a progress bar of the completed tests vs expected tests.

The expected tests can be obtained from the previous build, it might not be exact when tests are added or deleted but it should be close enough.

It would also be great if we could use the test duration to display some kind of count down timer. I know this cannot be accurate, especially if tests are run in parallel and the plugin has no way of knowing that, but still it can give an idea of progress vs time and not only vs number of tests.

One important thing though is to support test sets (not sure what they are called) to get the expected results for a given set only and not the full results of the job.

**Comment by dcendents** [comment]
@timja In reality my goal was always to calculate and expose the progress to other plugins to use them (in my case for the build monitor view).

My previous PR #9 was quite big because I was also adding an html view to the action. But this was never great, to update the progress bar we needed to refresh the page.

I will work on and submit a new simplified PR without the html view and only the API.
